### ISSUE TITLE
[REQUEST] Anonymous voting

### ISSUE THREAD

**Issue by apicella1** [Faithful-Resource-Pack/CompliBot#158]
There's a problem around compliance with the voting system. That problem is Bandwagoning. People usually vote on what they see as more popular. I feel this is also the case for new users as well. They aren't truly voting for something, rather voting for what other people are saying. 

one solution would be to introduce a button voting system as well as menus as nick has done done before. Combined with this, there should be an option in the menu to see the votes which will only be visible to the author. This ephemeral post could also have  a timestamp for when the last person voted on the texture. 

Additional Context: Nick knows everything and has been working on this before the typescript transfer.

**Comment by Pomi108** [comment]
It's not that easy. The votes need to be stored somewhere, ideally viewable by the original submitted so they can sill ping users and ask for feedback. That means we would probably have to involve the web app.

**Comment by nick-1666** [comment]
cant we just make a new collection on the db storing the message-id along with users who voted yes and those who voted no, like so:

```
{
    "id":"111111111111",
    "yes": 
        [
            "<user id>",
            "<other user id>",
            ...
        ],
    "no":
        [
            "<someone's user id>",
            ...
        ]
}
```

**Comment by nick-1666** [comment]
and on push to the db, we can delete these objects since their decisions are finalized anyways

**Comment by Pomi108** [comment]
could work, but again this would require some kind of ui on the web app and a link to it below the submission so that the original poster can view votes

**Comment by nick-1666** [comment]
although it isnt that easy, especially seeing as we haven't even had an implementation of the db on the new ts varient

**Comment by apicella1** [comment]
> It's not that easy. The votes need to be stored somewhere, ideally viewable by the original submitted so they can sill ping users and ask for feedback. That means we would probably have to involve the web app.

What Nick said, and Like I've said with the author seeing votes, " there should be an option in the menu to see the votes which will only be visible to the author."

**Comment by Juknum** [comment]
This has been implemented in the upcoming new submission system!
