### ISSUE TITLE
[Feature] Preparation for Overlay Compatibility

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/CompliBot#249]
*This issue goes in tandem with [App#110](https://github.com/Faithful-Resource-Pack/Discord-Bot/issues/249), [Database#4](https://github.com/Faithful-Resource-Pack/Database/issues/4), and [Api#30](https://github.com/Faithful-Resource-Pack/API/issues/30)*

Since [23w31a](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w31a) Minecraft allows resource packs to work with multiple pack formats at once. Overlays are a way for packs to provide files that need to be changed for them to work with a specific pack format without overwriting the base files of the pack. (More info in the linked minecraft.net article.)

While our software is technically mostly compatible with overlays aready, I am proposing some changes that, if implemented, would make the experience friendlier to end users and ensure nothing breaks in the future.

# Path Truncating
*Affects: Submission embed, texture choice menu, texture embed*

Overlay paths (i.e. Java paths *only* in version `java-latest` that don't start with `assets/`) should have their paths trimmed in all embeds and menus to remove the overlay prefix (`1.21/` for example) so that only the vanilla path starting with `assets/` is visible to the end user.

# Display Versions
*Affects: Submission embed, texture choice menu, texture embed*
- A new field for paths in the database
- Identical to the existing versions field in every way, except it doesn't set the repo branches to push textures to
- May not exist (so we don't have to edit every single path)
  - If this field doesn't exist, the regular versions field is used for display purposes
- Used for clarity in end user-facing UI (since all overlay paths are gonna be assigned to `java-latest`)

The existing embeds and menus should be modified to show display versions in place of regular versions where appropriate.

**Comment by 3vorp** [comment]
After months of discussion, many, _many_ potential solutions, and a lot of thought for edge cases, we've decided not to implement overlays into Faithful.

The main reasons include:
- Default and Faithful packs would have to be treated completely differently.
- Dots aren't allowed in overlay folder names, making overlay versions impossible either way.
- `/missing` as a concept would completely break.
- Branches and versions will no longer be synonymous, an assumption many things rely on.
- No good way of thresholding between real and display versions.
- `java-latest` would both exist and not exist at the same time in a really confusing state.
