### ISSUE TITLE
[Feature] Being able to see additional textures with /missing

### ISSUE THREAD

**Issue by HARYA301** [Faithful-Resource-Pack/CompliBot#254]
### Describe the feature you'd like

It would be cool that /missing has an argument to show blacklisted textures so they can be seen and made.

**Comment by 3vorp** [comment]
honestly I was just thinking in `blacklisted_textures.json` there would be a separate entry for modded like java and - bedrock, that would be toggled with the argument in /missing and would display missing textures alongside the regular missing textures
