### ISSUE TITLE
[Feature] Let users upload custom MCMETA files in /animate

### ISSUE THREAD

**Issue by Faithful-Pack** [Faithful-Resource-Pack/CompliBot#260]
*Issue originally created by `evorp` on Discord*

### Is your feature request related to a problem?

*No response*

### Describe the feature you'd like

Be able to upload (or paste) a valid MCMETA file into the bot, have the bot read it, and use those settings to animate the provided image.

### Notes

*No response*

**Comment by 3vorp** [comment]
completed with c09a38eea12654f4aad1abf960f2e88ca4f02b33
