### ISSUE TITLE
[Feature] reimplement /cycle and /compare loader using the gallery endpoint

### ISSUE THREAD

**Issue by Faithful-Pack** [Faithful-Resource-Pack/CompliBot#261]
*Issue originally created by `evorp` on Discord*

### Is your feature request related to a problem?

can be very very slow to load urls and generally take a while to stitch even small comparisons from it

### Describe the feature you'd like

instead of fetching every url manually using the api just fetch them all at once, since the gallery endpoint already does that (and even searches the texture iirc)

### Notes

not super urgent, but would probably optimize the command a good bit

**Comment by 3vorp** [comment]
completed with 2b4d00edc0fcd420ec76ae87af7f6b2df41fdad0
