### ISSUE TITLE
[Bug] Get Palette button breaks with animated texture

### ISSUE THREAD

**Issue by Faithful-Pack** [Faithful-Resource-Pack/CompliBot#272]
*Issue originally created by `Pythagoras_314` on Discord*

### What happened?

When clicking on the button, the palette is larger and just more wrong than intended. It should spit out the color palette as intended.

### To reproduce

1. Use /texture to grab an animated texture, such as fire_0.
2. Click on the eyedrop button to get the palette.

### Notes

*No response*

**Comment by 3vorp** [comment]
this is not accurate at all, what actually happened is that the image doesn't fall back to the thumbnail correctly and instead starts searching the channel
