### ISSUE TITLE
[Development] ts-node-dev is completely unnecessary now that nodemon supports TypeScript natively

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/CompliBot#282]
For me, `ts-node-dev` doesn't even actually apply the changed files on restart. [Nodemon supports TypeScript now](https://github.com/remy/nodemon/releases/tag/v1.19.0), so there's no reason we can't just switch to that, to make the dev workflow a bit better.

**Comment by TheRolfFR** [comment]
sure do, however we should compile the bot when using it to reduce power consumption, JS is far less power hungry than TS
