### ISSUE TITLE
[REQUEST] Adding optional version tag to the /texture command

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/CompliBot#30]
It would be good to have a version tag for the `/texture` command, to view older textures of the game.

For example, if you would want to see the old 1.16 ore textures, then you could use:
```
/texture 16 diamond_ore --ver 1.16
```
If you would want to see the newest one, then you could just not specify the tag.

**Comment by Juknum** [comment]
might be better to use something like this:
```
/texture 16 diamond_ore -v=1.16
```
OR:
```
/texture 16 diamond_ore --v=1.16
```

**Comment by TheRolfFR** [comment]
I suppose this is only for x16 resolution ?

**Comment by Juknum** [comment]
Should be for all resolutions
I'm moving this to the TS milestone since we would reimplement this using slash commands

**Comment by Pomi108** [comment]
Just wanted to say this is more high-priority now that Faithful 32x is going to support many versions at once

**Comment by 3vorp** [comment]
tbh is this relevant anymore? All version exclusives are added to the DB as-is anyways, there's usually no reason to search for a texture in a very specific version anymore — the textures should be the same regardless

**Comment by 3vorp** [comment]
upon further feedback it's not particularly necessary if #204 got implemented so this is getting shelved for the time being — we can bring it back later if necessary
